#ifndef CTIMETHREAD_GLOBAL_H
#define CTIMETHREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CTIMETHREAD_LIBRARY)
#  define CTIMETHREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CTIMETHREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CTIMETHREAD_GLOBAL_H
